name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Main application repository'
        required: true
      branch:
        description: 'PR branch to test'
        required: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Checkout main application repo
        run: |
          git clone --depth 1 --branch test https://x-access-token:${{ secrets.PLAYWRIGHT_TEST_REPO_TOKEN }}@github.com/dtoth-mono/main-app.git app

          cd app
          npm install
          npm start & 
          sleep 5

      - name: Checkout Playwright test repo
        uses: actions/checkout@v2

      - name: Install Playwright
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright tests
        id: playwright_tests
        continue-on-error: true
        run: |
          PLAYWRIGHT_JSON_OUTPUT_FILE=results.json npx playwright test --reporter=json
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "TEST_FAILED=true" >> $GITHUB_OUTPUT
          else
            echo "TEST_FAILED=false" >> $GITHUB_OUTPUT
          fi
          exit $exit_code

      - name: Playwright issue creator
        if: ${{ !cancelled() }}
        uses: estruyf/playwright-github-issue-creator@v1.3.0
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          report-path: results.json
          issue-prefix: "E2E: "
          issue-labels: "playwright, bug"
          add-project-label: true
          add-comment: true
          job-summary: true

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/**

      - name: Fail The Workflow if tests failed
        if: ${{ steps.playwright_tests.TEST_FAILED == 'true'}}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Some Tests Failed')